# Generated by Django 5.2.4 on 2025-07-05 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='meeting_recordings/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('audio_quality', models.CharField(choices=[('low', 'Low (32kbps)'), ('medium', 'Medium (64kbps)'), ('high', 'High (128kbps)'), ('premium', 'Premium (256kbps)')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='recording', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_enhanced', models.BooleanField(default=False)),
                ('noise_reduction_applied', models.BooleanField(default=False)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='meeting_recordings/originals/')),
                ('is_public', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('access_password', models.CharField(blank=True, max_length=50, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.meeting')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Recording',
                'verbose_name_plural': 'Meeting Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.meetingrecording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording Bookmark',
                'verbose_name_plural': 'Recording Bookmarks',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecordingTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('speakers_identified', models.BooleanField(default=False)),
                ('speaker_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='core.meetingrecording')),
            ],
            options={
                'verbose_name': 'Recording Transcript',
                'verbose_name_plural': 'Recording Transcripts',
            },
        ),
    ]
