# Generated by Django 5.2.4 on 2025-07-05 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetingrecording_recordingbookmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('engagement', 'Engagement Analysis'), ('participation', 'Participation Patterns'), ('productivity', 'Productivity Metrics'), ('sentiment', 'Sentiment Analysis'), ('topics', 'Topic Analysis'), ('recommendation', 'Recommendations')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('analysis_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('chart_data', models.JSONField(blank=True, default=dict)),
                ('chart_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_useful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Insight',
                'verbose_name_plural': 'Meeting Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('key_discussion_points', models.JSONField(default=list)),
                ('decisions_made', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_model_used', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='core.meeting')),
                ('transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recordingtranscript')),
            ],
            options={
                'verbose_name': 'Meeting Summary',
                'verbose_name_plural': 'Meeting Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('extracted_from_text', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='core.meeting')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_actions', to='core.meetingsummary')),
            ],
            options={
                'verbose_name': 'Action Item',
                'verbose_name_plural': 'Action Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaking_time_minutes', models.FloatField(default=0.0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('contributions_made', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('most_active_periods', models.JSONField(default=list)),
                ('topic_contributions', models.JSONField(default=dict)),
                ('sentiment_analysis', models.JSONField(default=dict)),
                ('participation_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='core.meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant Engagement',
                'verbose_name_plural': 'Participant Engagements',
                'ordering': ['-engagement_score'],
                'unique_together': {('meeting', 'participant')},
            },
        ),
    ]
